# This is a Python dictionary of ISO 3166-1 alpha-2 codes and their corresponding country names,
# as per official ISO site's data in [July 2015]
# https://web.archive.org/web/20150721184347/http://www.iso.org/iso/home/standards/country_codes/country_names_and_code_elements_txt-temp.htm

CountryCodes = {
    "Afghanistan":      {"Iso2": "AF", "Iso3": "AFG"},
    "Åland Islands":    {"Iso2": "AX", "Iso3": "ALA"},
    "Albania":          {"Iso2": "AL", "Iso3": "ALB"},
    "Algeria":          {"Iso2": "DZ", "Iso3": "DZA"},
    "American Samoa":   {"Iso2": "AS", "Iso3": "ASM"},
    "Andorra":          {"Iso2": "AD", "Iso3": "AND"},
    "Angola":           {"Iso2": "AO", "Iso3": "AGO"},
    "Anguilla":         {"Iso2": "AI", "Iso3": "AIA"},
    "Antarctica":       {"Iso2": "AQ", "Iso3": "ATA"},
    "Antigua and Barbuda": {"Iso2": "AG", "Iso3": "ATG"},
    "Argentina":        {"Iso2": "AR", "Iso3": "ARG"},
    "Armenia":          {"Iso2": "AM", "Iso3": "ARM"},
    "Aruba":            {"Iso2": "AW", "Iso3": "ABW"},
    "Australia":        {"Iso2": "AU", "Iso3": "AUS"},
    "Austria":          {"Iso2": "AT", "Iso3": "AUT"},
    "Azerbaijan":       {"Iso2": "AZ", "Iso3": "AZE"},
    "Bahamas":          {"Iso2": "BS", "Iso3": "BHS"},
    "Bahrain":          {"Iso2": "BH", "Iso3": "BHR"},
    "Bangladesh":       {"Iso2": "BD", "Iso3": "BGD"},
    "Barbados":         {"Iso2": "BB", "Iso3": "BRB"},
    "Belarus":          {"Iso2": "BY", "Iso3": "BLR"},
    "Belgium":          {"Iso2": "BE", "Iso3": "BEL"},
    "Belize":           {"Iso2": "BZ", "Iso3": "BLZ"},
    "Benin":            {"Iso2": "BJ", "Iso3": "BEN"},
    "Bermuda":          {"Iso2": "BM", "Iso3": "BMU"},
    "Bhutan": {"Iso2": "BT", "Iso3": "BTN"},
    "Bolivia": {"Iso2": "BO", "Iso3": "BOL"},
    "Burma": {"Iso2": "BU", "Iso3": "BUR"},
    "Saba": {"Iso2": "BQ", "Iso3": "BES"},
    "Bosnia and Herzegovina": {"Iso2": "BA", "Iso3": "BIH"},
    "Botswana": {"Iso2": "BW", "Iso3": "BWA"},
    "Bouvet Island": {"Iso2": "BV", "Iso3": "BVT"},
    "Brazil": {"Iso2": "BR", "Iso3": "BRA"},
    "British Indian Ocean Territory": {"Iso2": "IO", "Iso3": "IOT"},
    "Brunei": {"Iso2": "BN", "Iso3": "BRN"},
    "Bulgaria": {"Iso2": "BG", "Iso3": "BGR"},
    "Burkina Faso": {"Iso2": "BF", "Iso3": "BFA"},
    "Burundi": {"Iso2": "BI", "Iso3": "BDI"},
    # Spanish (English: Cape Verde)
    "Cabo Verde": {"Iso2": "CV", "Iso3": "CPV"},
    "Cambodia": {"Iso2": "KH", "Iso3": "KHM"},
    "Cameroon": {"Iso2": "CM", "Iso3": "CMR"},
    "Canada": {"Iso2": "CA", "Iso3": "CAN"},
    "Cayman Islands": {"Iso2": "KY", "Iso3": "CYM"},
    "Central African Republic": {"Iso2": "CF", "Iso3": "CAF"},
    "Chad": {"Iso2": "TD", "Iso3": "TCD"},
    "Chile": {"Iso2": "CL", "Iso3": "CHL"},
    "China": {"Iso2": "CN", "Iso3": "CHN"},
    "Christmas Island": {"Iso2": "CX", "Iso3": "CXR"},
    "Cocos Islands": {"Iso2": "CC", "Iso3": "CCK"},
    "Colombia": {"Iso2": "CO", "Iso3": "COL"},
    "Comoros": {"Iso2": "KM", "Iso3": "COM"},
    # Democratic Republic of the Congo
    "Congo (Kinshasa)": {"Iso2": "CD", "Iso3": "COD"},
    # Republic of the Congo
    "Congo (Brazzaville)": {"Iso2": "CG", "Iso3": "COG"},
    "Cook Islands": {"Iso2": "CK", "Iso3": "COK"},
    "Costa Rica": {"Iso2": "CR", "Iso3": "CRI"},
    # French (English: Ivory Coast)
    "Cote d'Ivoire": {"Iso2": "CI", "Iso3": "CIV"},
    "Croatia": {"Iso2": "HR", "Iso3": "HRV"},
    "Cuba": {"Iso2": "CU", "Iso3": "CUB"},
    "Curaçao": {"Iso2": "CW", "Iso3": "CUW"},
    "Cyprus": {"Iso2": "CY", "Iso3": "CYP"},
    "Czechia": {"Iso2": "CZ", "Iso3": "CZE"},
    "Denmark": {"Iso2": "DK", "Iso3": "DNK"},
    "Djibouti": {"Iso2": "DJ", "Iso3": "DJI"},
    "Dominica": {"Iso2": "DM", "Iso3": "DMA"},
    "Dominican Republic": {"Iso2": "DO", "Iso3": "DOM"},
    "Ecuador": {"Iso2": "EC", "Iso3": "ECU"},
    "Egypt": {"Iso2": "EG", "Iso3": "EGY"},
    "El Salvador": {"Iso2": "SV", "Iso3": "SLV"},
    "Equatorial Guinea": {"Iso2": "GQ", "Iso3": "GNQ"},
    "Eritrea": {"Iso2": "ER", "Iso3": "ERI"},
    "Estonia": {"Iso2": "EE", "Iso3": "EST"},
    "Eswatini": {"Iso2": "SZ", "Iso3": "SWZ"},
    "Ethiopia": {"Iso2": "ET", "Iso3": "ETH"},
    "Falkland Islands": {"Iso2": "FK", "Iso3": "FLK"},
    "Faroe Islands": {"Iso2": "FO", "Iso3": "FRO"},
    "Fiji": {"Iso2": "FJ", "Iso3": "FJI"},
    "Finland": {"Iso2": "FI", "Iso3": "FIN"},
    "France": {"Iso2": "FR", "Iso3": "FRA"},
    "French Guiana": {"Iso2": "GF", "Iso3": "GUF"},
    "French Polynesia": {"Iso2": "PF", "Iso3": "PYF"},
    "French Southern Territories": {"Iso2": "TF", "Iso3": "ATF"},
    "Gabon": {"Iso2": "GA", "Iso3": "GAB"},
    "Gambia": {"Iso2": "GM", "Iso3": "GMB"},
    "Georgia": {"Iso2": "GE", "Iso3": "GEO"},
    "Germany": {"Iso2": "DE", "Iso3": "DEU"},
    "Ghana": {"Iso2": "GH", "Iso3": "GHA"},
    "Gibraltar": {"Iso2": "GI", "Iso3": "GIB"},
    "Greece": {"Iso2": "GR", "Iso3": "GRC"},
    "Greenland": {"Iso2": "GL", "Iso3": "GRL"},
    "Grenada": {"Iso2": "GD", "Iso3": "GRD"},
    "Guadeloupe": {"Iso2": "GP", "Iso3": "GLP"},
    "Guam": {"Iso2": "GU", "Iso3": "GUM"},
    "Guatemala": {"Iso2": "GT", "Iso3": "GTM"},
    "Guernsey": {"Iso2": "GG", "Iso3": "GGY"},
    "Guinea": {"Iso2": "GN", "Iso3": "GIN"},
    "Guinea-Bissau": {"Iso2": "GW", "Iso3": "GNB"},
    "Guyana": {"Iso2": "GY", "Iso3": "GUY"},
    "Haiti": {"Iso2": "HT", "Iso3": "HTI"},
    "Heard Island and McDonald Islands": {"Iso2": "HM", "Iso3": "HMD"},
    "Holy See": {"Iso2": "VA", "Iso3": "VAT"},
    "Honduras": {"Iso2": "HN", "Iso3": "HND"},
    "Hong Kong": {"Iso2": "HK", "Iso3": "HKG"},
    "Hungary": {"Iso2": "HU", "Iso3": "HUN"},
    "Iceland": {"Iso2": "IS", "Iso3": "ISL"},
    "India": {"Iso2": "IN", "Iso3": "IND"},
    "Indonesia": {"Iso2": "ID", "Iso3": "IDN"},
    "Iran": {"Iso2": "IR", "Iso3": "IRN"},
    "Iraq": {"Iso2": "IQ", "Iso3": "IRQ"},
    "Ireland": {"Iso2": "IE", "Iso3": "IRL"},
    "Isle of Man": {"Iso2": "IM", "Iso3": "IMN"},
    "Israel": {"Iso2": "IL", "Iso3": "ISR"},
    "Italy": {"Iso2": "IT", "Iso3": "ITA"},
    "Jamaica": {"Iso2": "JM", "Iso3": "JAM"},
    "Japan": {"Iso2": "JP", "Iso3": "JPN"},
    "Jersey": {"Iso2": "JE", "Iso3": "JEY"},
    "Jordan": {"Iso2": "JO", "Iso3": "JOR"},
    "Kazakhstan": {"Iso2": "KZ", "Iso3": "KAZ"},
    "Kenya": {"Iso2": "KE", "Iso3": "KEN"},
    "Kiribati": {"Iso2": "KI", "Iso3": "KIR"},
    "Korea, South": {"Iso2": "KR", "Iso3": "KOR"},
    "Kosovo": {"Iso2": "XK", "Iso3": "XKX"},
    "Kuwait": {"Iso2": "KW", "Iso3": "KWT"},
    "Kyrgyzstan": {"Iso2": "KG", "Iso3": "KGZ"},
    "Laos": {"Iso2": "LA", "Iso3": "LAO"},
    "Latvia": {"Iso2": "LV", "Iso3": "LVA"},
    "Lebanon": {"Iso2": "LB", "Iso3": "LBN"},
    "Lesotho": {"Iso2": "LS", "Iso3": "LSO"},
    "Liberia": {"Iso2": "LR", "Iso3": "LBR"},
    "Libya": {"Iso2": "LY", "Iso3": "LBY"},
    "Liechtenstein": {"Iso2": "LI", "Iso3": "LIE"},
    "Lithuania": {"Iso2": "LT", "Iso3": "LTU"},
    "Luxembourg": {"Iso2": "LU", "Iso3": "LUX"},
    "Macau": {"Iso2": "MO", "Iso3": "MAC"},
    "North Macedonia": {"Iso2": "MK", "Iso3": "MKD"},
    "Madagascar": {"Iso2": "MG", "Iso3": "MDG"},
    "Malawi": {"Iso2": "MW", "Iso3": "MWI"},
    "Malaysia": {"Iso2": "MY", "Iso3": "MYS"},
    "Maldives": {"Iso2": "MV", "Iso3": "MDV"},
    "Mali": {"Iso2": "ML", "Iso3": "MLI"},
    "Malta": {"Iso2": "MT", "Iso3": "MLT"},
    "Marshall Islands": {"Iso2": "MH", "Iso3": "MHL"},
    "Martinique": {"Iso2": "MQ", "Iso3": "MTQ"},
    "Mauritania": {"Iso2": "MR", "Iso3": "MRT"},
    "Mauritius": {"Iso2": "MU", "Iso3": "MUS"},
    "Mayotte": {"Iso2": "YT", "Iso3": "MYT"},
    "Mexico": {"Iso2": "MX", "Iso3": "MEX"},
    "Micronesia": {"Iso2": "FM", "Iso3": "FSM"},
    "Moldova": {"Iso2": "MD", "Iso3": "MDA"},
    "Monaco": {"Iso2": "MC", "Iso3": "MCO"},
    "Mongolia": {"Iso2": "MN", "Iso3": "MNG"},
    "Montenegro": {"Iso2": "ME", "Iso3": "MNE"},
    "Montserrat": {"Iso2": "MS", "Iso3": "MSR"},
    "Morocco": {"Iso2": "MA", "Iso3": "MAR"},
    "Mozambique": {"Iso2": "MZ", "Iso3": "MOZ"},
    "Myanmar": {"Iso2": "MM", "Iso3": "MMR"},
    "Namibia": {"Iso2": "NA", "Iso3": "NAM"},
    "Nauru": {"Iso2": "NR", "Iso3": "NRU"},
    "Nepal": {"Iso2": "NP", "Iso3": "NPL"},
    "Netherlands": {"Iso2": "NL", "Iso3": "NLD"},
    "New Caledonia": {"Iso2": "NC", "Iso3": "NCL"},
    "New Zealand": {"Iso2": "NZ", "Iso3": "NZL"},
    "Nicaragua": {"Iso2": "NI", "Iso3": "NIC"},
    "Niger": {"Iso2": "NE", "Iso3": "NER"},
    "Nigeria": {"Iso2": "NG", "Iso3": "NGA"},
    "Niue": {"Iso2": "NU", "Iso3": "NIU"},
    "Norfolk Island": {"Iso2": "NF", "Iso3": "NFK"},
    "Northern Mariana Islands": {"Iso2": "MP", "Iso3": "MNP"},
    "North Korea": {"Iso2": "KP", "Iso3": "PRK"},
    "Norway": {"Iso2": "NO", "Iso3": "NOR"},
    "Oman": {"Iso2": "OM", "Iso3": "OMN"},
    "Pakistan": {"Iso2": "PK", "Iso3": "PAK"},
    "Palau": {"Iso2": "PW", "Iso3": "PLW"},
    "State of Palestine": {"Iso2": "PS", "Iso3": "PSE"},
    "Panama": {"Iso2": "PA", "Iso3": "PAN"},
    "Papua New Guinea": {"Iso2": "PG", "Iso3": "PNG"},
    "Paraguay": {"Iso2": "PY", "Iso3": "PRY"},
    "Peru": {"Iso2": "PE", "Iso3": "PER"},
    "Philippines": {"Iso2": "PH", "Iso3": "PHL"},
    "Pitcairn Islands": {"Iso2": "PN", "Iso3": "PCN"},
    "Poland": {"Iso2": "PL", "Iso3": "POL"},
    "Portugal": {"Iso2": "PT", "Iso3": "PRT"},
    "Puerto Rico": {"Iso2": "PR", "Iso3": "PRI"},
    "Qatar": {"Iso2": "QA", "Iso3": "QAT"},
    "Réunion": {"Iso2": "RE", "Iso3": "REU"},
    "Romania": {"Iso2": "RO", "Iso3": "ROU"},
    "Russia": {"Iso2": "RU", "Iso3": "RUS"},
    "Rwanda": {"Iso2": "RW", "Iso3": "RWA"},
    "Saint Barthélemy": {"Iso2": "BL", "Iso3": "BLM"},
    "Tristan da Cunha": {"Iso2": "SH", "Iso3": "SHN"},
    "Saint Kitts and Nevis": {"Iso2": "KN", "Iso3": "KNA"},
    "Saint Lucia": {"Iso2": "LC", "Iso3": "LCA"},
    "Collectivity of Saint Martin": {"Iso2": "MF", "Iso3": "MAF"},
    "Saint Pierre and Miquelon": {"Iso2": "PM", "Iso3": "SPM"},
    "Saint Vincent and the Grenadines": {"Iso2": "VC", "Iso3": "VCT"},
    "Samoa": {"Iso2": "WS", "Iso3": "WSM"},
    "San Marino": {"Iso2": "SM", "Iso3": "SMR"},
    "Sao Tome and Principe": {"Iso2": "ST", "Iso3": "STP"},
    "Saudi Arabia": {"Iso2": "SA", "Iso3": "SAU"},
    "Senegal": {"Iso2": "SN", "Iso3": "SEN"},
    "Serbia": {"Iso2": "RS", "Iso3": "SRB"},
    "Seychelles": {"Iso2": "SC", "Iso3": "SYC"},
    "Sierra Leone": {"Iso2": "SL", "Iso3": "SLE"},
    "Singapore": {"Iso2": "SG", "Iso3": "SGP"},
    "Sint Maarten": {"Iso2": "SX", "Iso3": "SXM"},
    "Slovakia": {"Iso2": "SK", "Iso3": "SVK"},
    "Slovenia": {"Iso2": "SI", "Iso3": "SVN"},
    "Solomon Islands": {"Iso2": "SB", "Iso3": "SLB"},
    "Somalia": {"Iso2": "SO", "Iso3": "SOM"},
    "South Africa": {"Iso2": "ZA", "Iso3": "ZAF"},
    "South Georgia and the South Sandwich Islands": {"Iso2": "GS", "Iso3": "SGS"},
    "South Sudan": {"Iso2": "SS", "Iso3": "SSD"},
    "Spain": {"Iso2": "ES", "Iso3": "ESP"},
    "Sri Lanka": {"Iso2": "LK", "Iso3": "LKA"},
    "Sudan": {"Iso2": "SD", "Iso3": "SDN"},
    "Suriname": {"Iso2": "SR", "Iso3": "SUR"},
    "Jan Mayen": {"Iso2": "SJ", "Iso3": "SJM"},
    "Swaziland": {"Iso2": "SZ", "Iso3": "SWZ"},
    "Sweden": {"Iso2": "SE", "Iso3": "SWE"},
    "Switzerland": {"Iso2": "CH", "Iso3": "CHE"},
    "Syria": {"Iso2": "SY", "Iso3": "SYR"},
    "Taiwan*": {"Iso2": "TW", "Iso3": "TWN"},
    "Tajikistan": {"Iso2": "TJ", "Iso3": "TJK"},
    "Tanzania": {"Iso2": "TZ", "Iso3": "TZA"},
    "Thailand": {"Iso2": "TH", "Iso3": "THA"},
    "Timor-Leste": {"Iso2": "TL", "Iso3": "TLS"},
    "Togo": {"Iso2": "TG", "Iso3": "TGO"},
    "Tokelau": {"Iso2": "TK", "Iso3": "TKL"},
    "Tonga": {"Iso2": "TO", "Iso3": "TON"},
    "Trinidad and Tobago": {"Iso2": "TT", "Iso3": "TTO"},
    "Tunisia": {"Iso2": "TN", "Iso3": "TUN"},
    "Turkey": {"Iso2": "TR", "Iso3": "TUR"},
    "Turkmenistan": {"Iso2": "TM", "Iso3": "TKM"},
    "Turks and Caicos Islands": {"Iso2": "TC", "Iso3": "TCA"},
    "Tuvalu": {"Iso2": "TV", "Iso3": "TUV"},
    "Uganda": {"Iso2": "UG", "Iso3": "UGA"},
    "Ukraine": {"Iso2": "UA", "Iso3": "UKR"},
    "United Arab Emirates": {"Iso2": "AE", "Iso3": "ARE"},
    "United Kingdom": {"Iso2": "GB", "Iso3": "GBR"},
    "United States Minor Outlying Islands": {"Iso2": "UM", "Iso3": "UMI"},
    "US": {"Iso2": "US", "Iso3": "USA"},
    "Uruguay": {"Iso2": "UY", "Iso3": "URY"},
    "Uzbekistan": {"Iso2": "UZ", "Iso3": "UZB"},
    "Vanuatu": {"Iso2": "VU", "Iso3": "VUT"},
    "Venezuela": {"Iso2": "VE", "Iso3": "VEN"},
    "Vietnam": {"Iso2": "VN", "Iso3": "VNM"},
    "British Virgin Islands": {"Iso2": "VG", "Iso3": "VGB"},
    "United States": {"Iso2": "VI", "Iso3": "VIR"},
    "Wallis and Futuna": {"Iso2": "WF", "Iso3": "WLF"},
    "Western Sahara": {"Iso2": "EH", "Iso3": "ESH"},
    "West Bank and Gaza": {"Iso2": "PS", "Iso3": "PS-"},
    "Yemen": {"Iso2": "YE", "Iso3": "YEM"},
    "Zambia": {"Iso2": "ZM", "Iso3": "ZMB"},
    "Zimbabwe": {"Iso2": "ZW", "Iso3": "ZWE"}
}
