language: python
python:
 - "3.9"
install:
 - pip install -e .
 - pip install pytest-cov codecov # Install packages for code coverage report
script:
 - pytest tests --cov=src tests # Point to the source directory
after_success:
 - codecov # uploads report to codecov.io